Structure Program
anurag-kqi/MI-7-systems pull request #29
Opened 2020-05-11 17:45 UTC by rupam88

#include <stdio.h>
#include <string.h>              `

struct Books  {
     char  title[50];
     char  author[50];
     char  subject[100];
     int   book_id;
 };
 
   // function declaration 
void 
printBook( struct Books book );

int 
main( )
 {
     struct Books Book1;        // Declare Book1 of type Book 
     struct Books Book2;        // Declare Book2 of type Book 

   // book 1 specification 
    strcpy( Book1.title, "Harry Potter");
    strcpy( Book1.author, "Elazin Plot");
    strcpy( Book1.subject, "The Dark Donuld Secretes");
    Book1.book_id = 1234;

   // book 2 specification 
    strcpy( Book2.title, "Way to success");
    strcpy( Book2.author, "Swami Vivekanand");
    strcpy( Book2.subject, "Will Power");
    Book2.book_id = 1126;

   // print Book1 info 
    printBook( Book1 );

   // Print Book2 info 
    printBook( Book2 );

    return 0;
}

void 
printBook( struct Books book ) {

   printf( "Book title : %s\n", book.title);
   printf( "Book author : %s\n", book.author);
   printf( "Book subject : %s\n", book.subject);
   printf( "Book book_id : %d\n", book.book_id);
}

2020-05-11 18:25 UTC, shankar7791 requested changes
change coding style add spaces, check curly braces

2020-05-12 10:55 UTC, shankar7791 approved these changes

2020-05-12 15:04 UTC, ASHWINI1494 approved these changes

2020-05-13 14:56 UTC, sakshi142 approved these changes

2020-05-14 15:53 UTC, merged